### ISSUE TITLE
jasmine-npm triggers deprecation warnings in jasmine-core

### ISSUE THREAD

**Issue by sgravrock** [jasmine/jasmine-npm#145]
It looks like jasmine-npm uses a couple of deprecated Env methods. If I install it in an empty directory, run `jasmine init`, and then run `jasmine`, I get a couple of deprecation warnings:

```
tunguska:jasmine steve$ yarn add jasmine
yarn add v1.3.2
(node:64721) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 13 new dependencies.
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.11
├─ concat-map@0.0.1
├─ fs.realpath@1.0.0
├─ glob@7.1.3
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ jasmine-core@3.3.0
├─ jasmine@3.3.0
├─ minimatch@3.0.4
├─ once@1.4.0
├─ path-is-absolute@1.0.1
└─ wrappy@1.0.2
✨  Done in 0.98s.
tunguska:jasmine steve$ ./node_modules/.bin/jasmine init
tunguska:jasmine steve$ ./node_modules/.bin/jasmine 
DEPRECATION: Setting throwOnExpectationFailure directly on Env is deprecated, please use the oneFailurePerSpec option in `configure`
DEPRECATION: Setting randomizeTests directly is deprecated, please use the random option in `configure`
[...]
```

**Comment by RobertMurry** [comment]
I'm brand new to using Jasmine.  I had a similar issue.  I fixed it with a "helper" with the following line:

```jasmine.getEnv().configure({random: false, oneFailurePerSpec: true});```

**Comment by vanduc1102** [comment]
i have this configuration 
```
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [],
  "oneFailurePerSpec": false,
  "random": false
}
```
but still have the issue, dont know why

**Comment by craigdfrench** [comment]
I changed `"random": false` to `"randomizeTests": false` and fixed things up for me.

**Comment by didaquis** [comment]
> I changed "random": false to "randomizeTests": false and fixed things up for me.

I did this, but now test are executing in random mode. I have setted to `false`!

**Comment by samuelt1** [comment]
is jasmine dead?

**Comment by Ithar** [comment]
Am also getting the same thing:
DEPRECATION: Setting throwOnExpectationFailure directly on Env is deprecated, please use the oneFailurePerSpec option in `configure`
DEPRECATION: Setting randomizeTests directly is deprecated, please use the random option in `configure`

Changing the configuration file did not help either.
